[workspace]
members = ["reddd", "reddd-macros"]

[workspace.package]
edition = "2021"
authors = ["Ayman Al-Qadhi <alqd@protonmail.com>"]
repository = "https://github.com/real-evolution/reddd"
license-file = "LICENSE"
readme = true
publish = true
