[package]
name = "reddd"
description = "Main crate"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
# external deps
chrono = { version = "0", features = ["serde"] }

# internal deps
reddd_macros = { path = "../reddd_macros" }

[dev-dependencies]
fake = { version = "2", features = ["derive"] }
rand = "0"
